version: "3"

services:
  web:
    image: openstreetmap-website:v1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432
  db:
    image: openstreetmap-db:v1
    build:
      context: ..
      dockerfile: docker/Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: openstreetmap
